Terraform debug

diff --git a/.github/workflows/test001-tf-plan-apply.yml b/.github/workflows/test001-tf-plan-apply.yml
--- a/.github/workflows/test001-tf-plan-apply.yml
+++ b/.github/workflows/test001-tf-plan-apply.yml
@@ -72,20 +72,30 @@ jobs:
         run: |
           echo "Terraform Plan..."
           terraform plan -detailed-exitcode -no-color -out tfplan
+          echo "Terraform Plan executed."
           exitcode=$?
+          echo "Terraform Plan exitcode variable set."
           echo "Terraform plan exit code: $exitcode"
-          echo "Terraform plan exit code: $exitcode" >> $GITHUB_OUTPUT
+          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
           echo "exitcode=$exitcode" >> $GITHUB_ENV
-          if [ "$exitcode" -eq 1 ]; then
-            echo "Terraform Plan Failed!" >&2
-            exit 1
-          elif [ "$exitcode" -eq 2 ]; then
-            echo "Terraform Plan found changes."
-            exit 0
-          else
-            echo "Terraform Plan found no changes."
-            exit 0
-          fi
+          case "$exitcode" in
+            1) 
+              echo "❌ Terraform Plan Failed!" >&2
+              exit 1
+              ;;
+            2) 
+              echo "✅ Terraform Plan found changes."
+              exit 0
+              ;;
+            0) 
+              echo "ℹ️ Terraform Plan found no changes."
+              exit 0
+              ;;
+            *) 
+              echo "⚠️ Unexpected exit code: $exitcode" >&2
+              exit 1
+              ;;
+          esac
 
       # Save plan to artifacts
       - name: Publish Terraform Plan
