Fix test001 tf

diff --git a/.github/workflows/test001-tf-plan-apply.yml b/.github/workflows/test001-tf-plan-apply.yml
--- a/.github/workflows/test001-tf-plan-apply.yml
+++ b/.github/workflows/test001-tf-plan-apply.yml
@@ -74,16 +74,16 @@ jobs:
           exitcode=$?
           echo "Terraform exit code: $exitcode"
           echo "exitcode=$exitcode" >> $GITHUB_ENV
-          if [ "$exitcode" -eq 1 ]; then
-            echo "Terraform Plan Failed!"
-            exit 1
-          elif [ "$exitcode" -eq 2 ]; then
-            echo "Terraform Plan found changes."
-            exit 0
-          else
-            echo "Terraform Plan found no changes."
-            exit 0
-          fi
+          # if [ "$exitcode" -eq 1 ]; then
+          #   echo "Terraform Plan Failed!"
+          #   exit 1
+          # elif [ "$exitcode" -eq 2 ]; then
+          #   echo "Terraform Plan found changes."
+          #   exit 0
+          # else
+          #   echo "Terraform Plan found no changes."
+          #   exit 0
+          # fi
 
       # Save plan to artifacts
       - name: Publish Terraform Plan
